var map,polyOptions={strokeColor:"#000000",strokeOpacity:1,strokeWeight:3,geodesic:!0},markersArray=[],linesArray=[],info=new google.maps.InfoWindow,ico=new google.maps.MarkerImage("s.png",new google.maps.Size(18,25),new google.maps.Point(302,306),new google.maps.Point(9,25)),shd=new google.maps.MarkerImage("s.png",new google.maps.Size(19,20),new google.maps.Point(283,311),new google.maps.Point(0,19)),icoa=new google.maps.MarkerImage("s.png",new google.maps.Size(19,35),new google.maps.Point(380,296),
new google.maps.Point(10,35)),shda=new google.maps.MarkerImage("s.png",new google.maps.Size(24,27),new google.maps.Point(356,304),new google.maps.Point(0,27)),icos=new google.maps.MarkerImage("s.png",new google.maps.Size(18,25),new google.maps.Point(338,306),new google.maps.Point(9,25)),icosa=new google.maps.MarkerImage("s.png",new google.maps.Size(19,35),new google.maps.Point(418,296),new google.maps.Point(10,35)),icof=new google.maps.MarkerImage("s.png",new google.maps.Size(18,25),new google.maps.Point(320,
306),new google.maps.Point(9,25)),icofa=new google.maps.MarkerImage("s.png",new google.maps.Size(19,35),new google.maps.Point(399,296),new google.maps.Point(10,35)),u=0,unit=[],gi=document.getElementById.bind(document),gn=document.getElementsByClassName.bind(document);unit[0]={dist:1/1852,volum:1,speed:1/1.852};unit[1]={dist:1/1605,volum:1/3.785411784,speed:1/1.605};unit[2]={dist:.001,volum:1,speed:1};
var unit_lbl=[{dist:"NM",vol:"L",speed:"kn"},{dist:"mi",vol:"gal",speed:"mph"},{dist:"km",vol:"L",speed:"kph"}],listener1,tool_route=!1,zoom=3;function createCookie(a,b,c){var d="";c&&(d=new Date,d.setTime(d.getTime()+864E5*c),d="; expires="+d.toUTCString());document.cookie=a+"="+b+d+"; path=/"}function getCookie(a){return(new RegExp("(?:; )?"+a+"=([^;]*);?")).test(document.cookie)?decodeURIComponent(RegExp.$1):null}
function coo(){createCookie("speed",parseFloat(gi("inp_speed").value),30);createCookie("conso",parseFloat(gi("inp_conso").value),30);createCookie("price",parseFloat(gi("inp_rate").value.replace(",",".")),30);createCookie("unit",u,30);createCookie("curen",gi("inp_mo").value,30);createCookie("zoom",zoom,30);createCookie("lat",map.getCenter().lat(),30);createCookie("lng",map.getCenter().lng(),30)}
function lat_dec2deg(a){var b=Math.floor(a),c=60*(a-b);return Math.abs(b).toString()+"\u00b0 "+Math.floor(c).toString()+"'"+Math.floor(60*(c-Math.floor(c))).toString()+'"'+(0>a?"S":"N")}function lng_dec2deg(a){var b=Math.floor(a),c=60*(a-b);return Math.abs(b).toString()+"\u00b0 "+Math.floor(c).toString()+"'"+Math.floor(60*(c-Math.floor(c))).toString()+'"'+(0>a?"W":"E")}
function hour(a){var b=0,c=Math.floor(a);24<=c&&(b=Math.floor(a/24),c-=24*b);a=Math.ceil(60*(a-24*b-c));59<a&&(c++,a-=60);return(0<b?b.toString()+" day ":"")+c.toString()+" hrs "+a.toString()+" min"}function change_unit(a){var b=u;u=a;gi("inp_speed").value=parseFloat(gi("inp_speed").value)/unit[b].speed*unit[u].speed;gi("inp_conso").value=parseFloat(gi("inp_conso").value)/unit[b].volum*unit[u].volum}function update_class(a,b){for(var c=gn(a),d=0;d<c.length;d++)c[d].innerHTML=b}
function update_unit(){update_class("lbl_dist",unit_lbl[u].dist);update_class("lbl_vol",unit_lbl[u].vol);update_class("lbl_speed",unit_lbl[u].speed);update_class("lbl_mo",gi("inp_mo").value)}function round(a,b){var c=Math.pow(10,b);return Math.round(a*c)/c}function zf(a){return 10>a?"0"+a:a}
function m2s(){var a;var b=markersArray.length;var c=markersArray[0].getPosition();var d="[["+c.lat()+","+c.lng()+"]";for(a=1;a<b;a++)c=markersArray[a].getPosition(),d+=",["+c.lat()+","+c.lng()+"]";return d+"]"}function s2m(a){var b;a=eval(a);var c=a.length;reset_poly();console.log(c);var d=1;100<c&&(d=5);for(b=0;b<c;b+=d)addLatLng(new google.maps.LatLng(a[b][0],a[b][1]));update_poly(!0)}
function add2seg(a,b){var c;var d=markersArray.length;var f=[];for(c=0;c<a;c++){var e=markersArray[c].getPosition();e=[e.lat(),e.lng()];f.push(e)}e=[b.lat(),b.lng()];for(f.push(e);c<d;c++)e=markersArray[c].getPosition(),e=[e.lat(),e.lng()],f.push(e);reset_poly();for(c=0;c<=d;c++)addLatLng(new google.maps.LatLng(f[c][0],f[c][1]));update_poly(!0)}
function uMark(){var a;markersArray[0].setIcon(icos);for(a=1;a<markersArray.length-1;a++)markersArray[a].setIcon(ico);1<markersArray.length&&markersArray[a].setIcon(icof)}
function printRt(){var a=window.open("","","width=600,height=800");a.document.write('<!DOCTYPE html><html><head><title>Satsee - Route calculator</title><link rel="stylesheet" type="text/css"href="default.css" /></head><body>');a.document.write("<h1>Satsee route calculator</h1>");a.document.write("<p>Navigation summary :</p>");a.document.write("<p>Distance : "+gi("res_dist").innerHTML+" "+gn("lbl_dist")[0].innerHTML+"<br>Duration : "+gi("res_time").innerHTML+"<br>Fuel consumption : "+gi("res_vol").innerHTML+
" "+gn("lbl_vol")[0].innerHTML+"<br>Cruise fuel rate : "+gi("res_price").innerHTML+" "+gn("lbl_mo")[0].innerHTML+"</p>");a.document.write("<p>Route details :</p>");a.document.write(gi("tbc1_3_path").innerHTML);a.document.write("</body></html>");a.focus();a.print()}
function update_calc(){var a=0,b=markersArray.length,c="no data",d=parseFloat(gi("inp_speed").value),f="";update_unit();0<b?createCookie("path",m2s(),30):createCookie("path","",-30);if(1<b){c="";for(var e=1;e<b;e++){var h=markersArray[e-1].getPosition();var g=markersArray[e].getPosition();var l=h.lat();var m=h.lng();h=g.lat();g=g.lng();l=distVincenty(l,m,h,g);m=e/2===Math.round(e/2)?"pdetp":"pdeti";g=round(l.initialBearing,1);0>g&&(g+=360);h=l.distance*unit[u].dist/d;var k=Math.round(36E4*h)/100;
f=1===e?f+k.toString():f+(","+k.toString());k=e.toString();c+='<div id="pdet'+k+'" class="pdet '+m+'" onmouseover="hline('+k+');" onmouseout="uline('+k+');">&nbsp;<span class="c1">'+zf(k)+'</span> - <span class="c2">heading : '+g.toString()+'\u00b0</span> - <span class="c3">distance : '+round(l.distance*unit[u].dist,1).toString()+unit_lbl[u].dist+'</span> - <span class="c4">time : '+hour(h)+"</span></div>\n";a+=parseFloat(l.distance)}createCookie("time",f,30)}gi("tbc1_3_path").innerHTML=c;gi("res_dist").innerHTML=
round(a*unit[u].dist,3);c=0;0!==d&&(c=a*unit[u].dist/d);gi("res_time").innerHTML=hour(c);a=parseFloat(gi("inp_conso").value);gi("res_vol").innerHTML=round(c*a,1);d=parseFloat(gi("inp_rate").value.replace(",","."));gi("res_price").innerHTML=round(c*a*d,2);1<markersArray.length&&gi("pdet"+(markersArray.length-1)).scrollIntoView();0<b&&uMark()}
function hide_poly(){if(linesArray){for(var a in linesArray)Object.prototype.hasOwnProperty.call(linesArray,a)&&linesArray[a].getPath().clear();linesArray.length=0}}function hline(a){linesArray[a].setOptions({strokeColor:"#ff9933",strokeWeight:5})}function uline(a){linesArray[a].setOptions({strokeColor:"#000000",strokeWeight:3})}
function update_poly(a){if(a&&(hide_poly(),a=markersArray.length,1<a))for(var b=1;b<a;b++)linesArray[b]=new google.maps.Polyline(polyOptions),linesArray[b].setMap(map),linesArray[b].dsbid=b.toString(),linesArray[b].getPath().push(markersArray[b-1].position),linesArray[b].getPath().push(markersArray[b].position),google.maps.event.addListener(linesArray[b],"mouseover",function(){this.setOptions({strokeColor:"#ff9933",strokeWeight:5});gi("pdet"+this.dsbid).classList.add("pdeta");gi("pdet"+this.dsbid).scrollIntoView()}),
google.maps.event.addListener(linesArray[b],"mouseout",function(){this.setOptions({strokeColor:"#000000",strokeWeight:3});gi("pdet"+this.dsbid).classList.remove("pdeta")}),google.maps.event.addListener(linesArray[b],"click",function(c){add2seg(this.dsbid,c.latLng)});update_calc()}function reset_poly(){var a;if(markersArray){for(a in markersArray)Object.prototype.hasOwnProperty.call(markersArray,a)&&markersArray[a].setMap(null);markersArray.length=0}hide_poly();update_calc()}
function deleteMarker(a){markersArray[a].setMap(null);markersArray.splice(a,1);s2m(m2s())}function deleteLast(){deleteMarker(markersArray.length-1)}function myConfirm(a,b,c){var d;gi("box_ttl").innerHTML=a;gi("box_txt").innerHTML=b;a="";for(d in c)a+='<input type="button" value="'+d+'" title="'+d+'" onclick="'+c[d]+'" class="cbtn">';gi("box_btn").innerHTML=a;gi("confirm").style.display="block"}function cHide(){gi("confirm").style.display="none"}
function showDel(){myConfirm("delete","Which marker do you want to delete ?",{All:"cHide();reset_poly();",Last:"cHide();deleteLast();",None:"cHide();"})}function showImp(){gi("box_ttl").innerHTML="import GPX";gi("box_txt").innerHTML="Select GPX file";gi("box_btn").innerHTML='<input type="file" id="input" onchange="loadGPX(this.files[0])">';gi("confirm").style.display="block"}var file=new FileReader,xml;
function loadGPX(a){cHide();file.readAsText(a);file.onload=function(b){xml=(new DOMParser).parseFromString(file.result,"text/xml");trkpt=xml.getElementsByTagName("trkpt");b="[";for(var c=0;c<trkpt.length;c++)b+="["+trkpt[c].getAttribute("lat")+","+trkpt[c].getAttribute("lon")+"],";s2m(b+"]")}}function rClick(a){myConfirm("delete marker","Are you sure you want to delete marker #"+(a+1).toString()+" ?",{Yes:"deleteMarker("+a.toString()+");cHide();",No:"cHide();"})}
function infocont(a){var b=a.dsbid;return"<h3>Marker #"+(b+1)+"</h3><p>Latitude : "+lat_dec2deg(a.position.lat())+"<br />Longitude : "+lng_dec2deg(a.position.lng())+'</p><p><input type="button" value="delete" onClick="setTimeout(\'info.close();rClick('+b+');\',100);" class="wbtn" /></p>'}function infow(a){info.setContent(infocont(a));info.open(map,a)}
function addLatLng(a){a=new google.maps.Marker({position:a,draggable:!0,cursor:"move",icon:ico,shadow:shd,title:"#"+(markersArray.length+1),map:map});a.dsbid=markersArray.length;google.maps.event.addListener(a,"mouseup",function(){update_poly(!0)});google.maps.event.addListener(a,"rightclick",function(){rClick(this.dsbid)});google.maps.event.addListener(a,"mouseover",function(){0===this.dsbid?this.setIcon(icosa):this.dsbid===markersArray.length-1?this.setIcon(icofa):this.setIcon(icoa);this.setShadow(shda)});
google.maps.event.addListener(a,"mouseout",function(){0===this.dsbid?this.setIcon(icos):this.dsbid===markersArray.length-1?this.setIcon(icof):this.setIcon(ico);this.setShadow(shd)});google.maps.event.addListener(a,"drag",function(){info.setContent(infocont(this));update_poly(!1)});google.maps.event.addListener(a,"click",function(){infow(this)});markersArray.push(a)}var ctm,cl,cs;ctm=0;cs=!1;function addl(){addLatLng(cl);update_poly(!0);cs=!1}
function manageClick(a){cs?(clearTimeout(ctm),cs=!1):(cs=!0,cl=a,ctm=setTimeout("addl()",100))}
function route(a){if(tool_route!==a){a?(listener1=google.maps.event.addListener(map,"click",function(c){manageClick(c.latLng)}),listener2=google.maps.event.addListener(map,"dblclick",function(c){cs=!0;manageClick(c.latLng)}),update_poly(!0)):(google.maps.event.removeListener(listener1),google.maps.event.removeListener(listener2),hide_poly());if(markersArray)for(var b in markersArray)Object.prototype.hasOwnProperty.call(markersArray,b)&&markersArray[b].setVisible(a);tool_route=a}}
function update_zoom(){zoom=map.getZoom();coo()}function update_center(){(new google.maps.MaxZoomService).getMaxZoomAtLatLng(map.getCenter(),function(a){map.setOptions({maxZoom:a.zoom})});update_zoom()}
function init_map(){var a=parseFloat(getCookie("lat"));isNaN(a)&&(a=30);var b=parseFloat(getCookie("lng"));isNaN(b)&&(b=0);zoom=parseInt(getCookie("zoom"));isNaN(zoom)&&(zoom=3);a=new google.maps.LatLng(a,b);a={zoom:zoom,center:a,mapTypeId:"satsee",disableDefaultUI:!0,scaleControl:!0,minZoom:3};map=new google.maps.Map(gi("map_canvas"),a);a=new google.maps.StyledMapType([{featureType:"road",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"administrative",elementType:"all",stylers:[{lightness:0},
{saturation:0},{hue:"#ffffff"},{invert_lightness:!1},{visibility:"on"}]},{featureType:"administrative",elementType:"geometry",stylers:[{visibility:"off"}]},{featureType:"administrative.country",elementType:"all",stylers:[{lightness:0},{saturation:0},{hue:"#ffffff"},{invert_lightness:!1},{visibility:"on"}]},{featureType:"poi",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"transit",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"landscape",elementType:"all",stylers:[{hue:"#ffffff"},
{lightness:0}]},{featureType:"water",elementType:"all",stylers:[{hue:"#3399ff"},{lightness:0},{saturation:100},{invert_lightness:!1},{gamma:1},{visibility:"on"}]}],{name:"Satsee"});map.mapTypes.set("satsee",a);google.maps.event.addListener(map,"mousemove",function(c){gi("coords").innerHTML='Lat: <span class="coord">'+lat_dec2deg(c.latLng.lat().toString())+'</span> Lon: <span class="coord">'+lng_dec2deg(c.latLng.lng().toString())+"</span>"});google.maps.event.addListener(map,"zoom_changed",update_zoom);
google.maps.event.addListener(map,"center_changed",update_center);update_zoom();a=getCookie("path");null!==a&&s2m(a)}function address(a){(new google.maps.Geocoder).geocode({address:a},function(b){map.fitBounds(b[0].geometry.viewport)})}
function select_menu(a){var b;route(!0);for(b=1;3>=b;b++)gi("m"+b).classList.add("mi"+b),gi("m"+b).classList.remove("ma"+b),gi("tbc"+b).style.display="none";0!==a&&(gi("m"+a).classList.remove("mi"+a),gi("m"+a).classList.add("ma"+a),gi("tbc"+a).style.display="block")}
function change_map_type(a){switch(a){case "0":map.setMapTypeId(google.maps.MapTypeId.SATELLITE);break;case "1":map.setMapTypeId(google.maps.MapTypeId.HYBRID);break;case "2":map.setMapTypeId(google.maps.MapTypeId.ROADMAP);break;case "3":map.setMapTypeId(google.maps.MapTypeId.TERRAIN);break;case "4":map.setMapTypeId("satsee");break;default:map.setMapTypeId(google.maps.MapTypeId.SATELLITE)}update_zoom()}
function GetDomOffset(a,b){for(;a&&"BODY"!=a.tagName;)eval("i += o."+b+";"),a=a.offsetParent;return 0}document.addEventListener("DOMContentLoaded",function(){init_map();select_menu(2);gi("search").onmousedown=function(a){17>(a||event).clientX-GetDomOffset(gi("search"),"offsetLeft")&&address(gi("search").value)}});